apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ds-plugin-bundle-poc
resources:
  - rendered/base.yaml
patches:
  - path: patch-api.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: ds-plugin-bundle-poc-api
  - path: patch-master.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: ds-plugin-bundle-poc-master
  - path: patch-worker.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: ds-plugin-bundle-poc-worker
